name: "\U0001F41B Bug Report"
description: Report your bug here.
labels: ["bug"]
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Any information you can provide about your system and the issue you encountered will help to resolve it faster.

  - type: checkboxes
    attributes:
      label: Have you searched existing issues?  🔎
      description: Please search to see if an [issue](https://github.com/MaartenGr/BERTopic/issues) already exists for the issue you encountered.
      options:
        - label: I have searched and found no existing issues
          required: true

  - type: textarea
    id: describe_the_bug
    attributes:
      label: Desribe the bug
      description: Please provide a concise description of the bug. If there is an error, make sure to provide the **full** error log.
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a minimal example, with code, that can be run to reproduce the issue.
      value: |
        ```python
        from bertopic import BERTopic
        
        ```

  - type: input
    id: bertopic_version
    attributes:
      label: BERTopic Version
      description: What version of BERTopic are you using?
    validations:
      required: true
