blank_issues_enabled: true
contact_links:
  - name: 💡 General questions
    url: https://github.com/MaartenGr/BERTopic/discussions
    about: Ask a question there!
  - name: Want to contribute?
    url: https://github.com/MaartenGr/BERTopic/blob/master/CONTRIBUTING.md
    about: Head to the contributing guidelines
