# All models, as of 13/12/2020, pretrained for sentence transformers
embedding_models = ['LaBSE',
                   'average_word_embeddings_glove.6B.300d',
                   'average_word_embeddings_glove.840B.300d',
                   'average_word_embeddings_komninos',
                   'average_word_embeddings_levy_dependency',
                   'bert-base-nli-cls-token',
                   'bert-base-nli-max-tokens',
                   'bert-base-nli-mean-tokens',
                   'bert-base-nli-stsb-mean-tokens',
                   'bert-base-nli-stsb-wkpooling',
                   'bert-base-nli-wkpooling',
                   'bert-base-wikipedia-sections-mean-tokens',
                   'bert-large-nli-cls-token',
                   'bert-large-nli-max-tokens',
                   'bert-large-nli-mean-tokens',
                   'bert-large-nli-stsb-mean-tokens',
                   'distilbert-base-nli-max-tokens',
                   'distilbert-base-nli-mean-tokens',
                   'distilbert-base-nli-stsb-mean-tokens',
                   'distilbert-base-nli-stsb-quora-ranking',
                   'distilbert-base-nli-stsb-wkpooling',
                   'distilbert-base-nli-wkpooling',
                   'distilbert-multilingual-nli-stsb-quora-ranking',
                   'distilroberta-base-msmarco-v1',
                   'distilroberta-base-msmarco-v2',
                   'distilroberta-base-paraphrase-v1',
                   'distiluse-base-multilingual-cased-v1',
                   'distiluse-base-multilingual-cased-v2',
                   'distiluse-base-multilingual-cased',
                   'roberta-base-nli-mean-tokens',
                   'roberta-base-nli-stsb-mean-tokens',
                   'roberta-base-nli-stsb-wkpooling',
                   'roberta-base-nli-wkpooling',
                   'roberta-large-nli-mean-tokens',
                   'roberta-large-nli-stsb-mean-tokens',
                   'xlm-r-100langs-bert-base-nli-mean-tokens',
                   'xlm-r-100langs-bert-base-nli-stsb-mean-tokens',
                   'xlm-r-base-en-ko-nli-ststb',
                   'xlm-r-bert-base-nli-mean-tokens',
                   'xlm-r-bert-base-nli-stsb-mean-tokens',
                   'xlm-r-distilroberta-base-paraphrase-v1',
                   'xlm-r-large-en-ko-nli-ststb']

languages = ['afrikaans', 'albanian', 'amharic', 'arabic', 'armenian', 'assamese',
             'azerbaijani', 'basque', 'belarusian', 'bengali', 'bengali romanize',
             'bosnian', 'breton', 'bulgarian', 'burmese', 'burmese zawgyi font', 'catalan',
             'chinese (simplified)', 'chinese (traditional)', 'croatian', 'czech', 'danish',
             'dutch', 'english', 'esperanto', 'estonian', 'filipino', 'finnish', 'french',
             'galician', 'georgian', 'german', 'greek', 'gujarati', 'hausa', 'hebrew', 'hindi',
             'hindi romanize', 'hungarian', 'icelandic', 'indonesian', 'irish', 'italian', 'japanese',
             'javanese', 'kannada', 'kazakh', 'khmer', 'korean', 'kurdish (kurmanji)', 'kyrgyz',
             'lao', 'latin', 'latvian', 'lithuanian', 'macedonian', 'malagasy', 'malay', 'malayalam',
             'marathi', 'mongolian', 'nepali', 'norwegian', 'oriya', 'oromo', 'pashto', 'persian',
             'polish', 'portuguese', 'punjabi', 'romanian', 'russian', 'sanskrit', 'scottish gaelic',
             'serbian', 'sindhi', 'sinhala', 'slovak', 'slovenian', 'somali', 'spanish', 'sundanese',
             'swahili', 'swedish', 'tamil', 'tamil romanize', 'telugu', 'telugu romanize', 'thai',
             'turkish', 'ukrainian', 'urdu', 'urdu romanize', 'uyghur', 'uzbek', 'vietnamese',
             'welsh', 'western frisian', 'xhosa', 'yiddish']
