# All models, as of 13/12/2020, pretrained for sentence transformers
embedding_models = ['LaBSE',
                   'average_word_embeddings_glove.6B.300d',
                   'average_word_embeddings_glove.840B.300d',
                   'average_word_embeddings_komninos',
                   'average_word_embeddings_levy_dependency',
                   'bert-base-nli-cls-token',
                   'bert-base-nli-max-tokens',
                   'bert-base-nli-mean-tokens',
                   'bert-base-nli-stsb-mean-tokens',
                   'bert-base-nli-stsb-wkpooling',
                   'bert-base-nli-wkpooling',
                   'bert-base-wikipedia-sections-mean-tokens',
                   'bert-large-nli-cls-token',
                   'bert-large-nli-max-tokens',
                   'bert-large-nli-mean-tokens',
                   'bert-large-nli-stsb-mean-tokens',
                   'distilbert-base-nli-max-tokens',
                   'distilbert-base-nli-mean-tokens',
                   'distilbert-base-nli-stsb-mean-tokens',
                   'distilbert-base-nli-stsb-quora-ranking',
                   'distilbert-base-nli-stsb-wkpooling',
                   'distilbert-base-nli-wkpooling',
                   'distilbert-multilingual-nli-stsb-quora-ranking',
                   'distilroberta-base-msmarco-v1',
                   'distilroberta-base-msmarco-v2',
                   'distilroberta-base-paraphrase-v1',
                   'distiluse-base-multilingual-cased-v1',
                   'distiluse-base-multilingual-cased-v2',
                   'distiluse-base-multilingual-cased',
                   'roberta-base-nli-mean-tokens',
                   'roberta-base-nli-stsb-mean-tokens',
                   'roberta-base-nli-stsb-wkpooling',
                   'roberta-base-nli-wkpooling',
                   'roberta-large-nli-mean-tokens',
                   'roberta-large-nli-stsb-mean-tokens',
                   'xlm-r-100langs-bert-base-nli-mean-tokens',
                   'xlm-r-100langs-bert-base-nli-stsb-mean-tokens',
                   'xlm-r-base-en-ko-nli-ststb',
                   'xlm-r-bert-base-nli-mean-tokens',
                   'xlm-r-bert-base-nli-stsb-mean-tokens',
                   'xlm-r-distilroberta-base-paraphrase-v1',
                   'xlm-r-large-en-ko-nli-ststb']

languages = [
    'Afrikaans', 'Albanian', 'Amharic', 'Arabic', 'Armenian', 'Assamese',
    'Azerbaijani', 'Basque', 'Belarusian', 'Bengali', 'Bengali Romanize', 'Bosnian',
    'Breton', 'Bulgarian', 'Burmese', 'Burmese zawgyi font', 'Catalan', 'Chinese (Simplified)',
    'Chinese (Traditional)', 'Croatian', 'Czech', 'Danish', 'Dutch', 'English', 'Esperanto',
    'Estonian', 'Filipino', 'Finnish', 'French', 'Galician', 'Georgian', 'German', 'Greek',
    'Gujarati', 'Hausa', 'Hebrew', 'Hindi', 'Hindi Romanize', 'Hungarian', 'Icelandic', 'Indonesian',
    'Irish', 'Italian', 'Japanese', 'Javanese', 'Kannada', 'Kazakh', 'Khmer', 'Korean',
    'Kurdish (Kurmanji)', 'Kyrgyz', 'Lao', 'Latin', 'Latvian', 'Lithuanian', 'Macedonian',
    'Malagasy', 'Malay', 'Malayalam', 'Marathi', 'Mongolian', 'Nepali', 'Norwegian',
    'Oriya', 'Oromo', 'Pashto', 'Persian', 'Polish', 'Portuguese', 'Punjabi', 'Romanian',
    'Russian', 'Sanskrit', 'Scottish Gaelic', 'Serbian', 'Sindhi', 'Sinhala', 'Slovak',
    'Slovenian', 'Somali', 'Spanish', 'Sundanese', 'Swahili', 'Swedish', 'Tamil',
    'Tamil Romanize', 'Telugu', 'Telugu Romanize', 'Thai', 'Turkish', 'Ukrainian',
    'Urdu', 'Urdu Romanize', 'Uyghur', 'Uzbek', 'Vietnamese', 'Welsh', 'Western Frisian',
    'Xhosa', 'Yiddish'
]
