import numpy as np
from typing import Any
from sklearn.metrics.pairwise import cosine_similarity
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from bertopic import BERTopic


def reduce_outliers(
    topic_model: "BERTopic",
    documents: list[str],
    topics: list[int],
    images: list[str] | None = None,
    strategy: str = "distributions",
    probabilities: np.ndarray = None,
    threshold: float = 0,
    embeddings: np.ndarray = None,
    distributions_params: dict[str, Any] = {},
) -> list[int]:
    """Reduce outliers by merging them with their nearest topic according
    to one of several strategies.

    When using HDBSCAN, DBSCAN, or OPTICS, a number of outlier documents might be created
    that do not fall within any of the created topics. These are labeled as -1.
    This function allows the user to match outlier documents with their nearest topic
    using one of the following strategies using the `strategy` parameter:
        * "probabilities"
            This uses the soft-clustering as performed by HDBSCAN to find the
            best matching topic for each outlier document. To use this, make
            sure to calculate the `probabilities` beforehand by instantiating
            BERTopic with `calculate_probabilities=True`.
        * "distributions"
            Use the topic distributions, as calculated with `.approximate_distribution`
            to find the most frequent topic in each outlier document. You can use the
            `distributions_params` variable to tweak the parameters of
            `.approximate_distribution`.
        * "c-tf-idf"
            Calculate the c-TF-IDF representation for each outlier document and
            find the best matching c-TF-IDF topic representation using
            cosine similarity.
        * "embeddings"
            Using the embeddings of each outlier documents, find the best
            matching topic embedding using cosine similarity.

    Arguments:
        topic_model: The BERTopic instance
        documents: A list of documents for which we reduce or remove the outliers.
        topics: The topics that correspond to the documents
        images: A list of paths to the images used when calling either
                `fit` or `fit_transform`
        strategy: The strategy used for reducing outliers.
                Options:
                    * "probabilities"
                        This uses the soft-clustering as performed by HDBSCAN
                        to find the best matching topic for each outlier document.

                    * "distributions"
                        Use the topic distributions, as calculated with `.approximate_distribution`
                        to find the most frequent topic in each outlier document.

                    * "c-tf-idf"
                        Calculate the c-TF-IDF representation for outlier documents and
                        find the best matching c-TF-IDF topic representation.

                    * "embeddings"
                        Calculate the embeddings for outlier documents and
                        find the best matching topic embedding.
        probabilities: Probabilities generated by HDBSCAN for each document when using the strategy `"probabilities"`.
        threshold: The threshold for assigning topics to outlier documents. This value
                    represents the minimum probability when `strategy="probabilities"`.
                    For all other strategies, it represents the minimum similarity.
        embeddings: The pre-computed embeddings to be used when `strategy="embeddings"`.
                    If this is None, then it will compute the embeddings for the outlier documents.
        distributions_params: The parameters used in `.approximate_distribution` when using
                                the strategy `"distributions"`.

    Returns:
        new_topics: The updated topics

    Usage:

    The default settings uses the `"distributions"` strategy:

    ```python
    new_topics = topic_model.reduce_outliers(docs, topics)
    ```

    When you use the `"probabilities"` strategy, make sure to also pass the probabilities
    as generated through HDBSCAN:

    ```python
    from bertopic import BERTopic
    topic_model = BERTopic(calculate_probabilities=True)
    topics, probs = topic_model.fit_transform(docs)

    new_topics = topic_model.reduce_outliers(docs, topics, probabilities=probs, strategy="probabilities")
    ```
    """
    if not topic_model._outliers:
        raise ValueError("No outliers to reduce.")

    if images is not None:
        strategy = "embeddings"

    # Check correct use of parameters
    if strategy.lower() == "probabilities" and probabilities is None:
        raise ValueError("Make sure to pass in `probabilities` in order to use the probabilities strategy")

    # Reduce outliers by extracting most likely topics through the topic-term probability matrix
    if strategy.lower() == "probabilities":
        new_topics = [
            np.argmax(prob) if np.max(prob) >= threshold and topic == -1 else topic
            for topic, prob in zip(topics, probabilities)
        ]

    # Reduce outliers by extracting most frequent topics through calculating of Topic Distributions
    elif strategy.lower() == "distributions":
        outlier_ids = [index for index, topic in enumerate(topics) if topic == -1]
        outlier_docs = [documents[index] for index in outlier_ids]
        topic_distr, _ = topic_model.approximate_distribution(
            outlier_docs, min_similarity=threshold, **distributions_params
        )
        outlier_topics = iter([np.argmax(prob) if sum(prob) > 0 else -1 for prob in topic_distr])
        new_topics = [topic if topic != -1 else next(outlier_topics) for topic in topics]

    # Reduce outliers by finding the most similar c-TF-IDF representations
    elif strategy.lower() == "c-tf-idf":
        outlier_ids = [index for index, topic in enumerate(topics) if topic == -1]
        outlier_docs = [documents[index] for index in outlier_ids]

        # Calculate c-TF-IDF of outlier documents with all topics
        bow_doc = topic_model.vectorizer_model.transform(outlier_docs)
        c_tf_idf_doc = topic_model.ctfidf_model.transform(bow_doc)
        similarity = cosine_similarity(c_tf_idf_doc, topic_model.c_tf_idf_[topic_model._outliers :])

        # Update topics
        similarity[similarity < threshold] = 0
        outlier_topics = iter([np.argmax(sim) if sum(sim) > 0 else -1 for sim in similarity])
        new_topics = [topic if topic != -1 else next(outlier_topics) for topic in topics]

    # Reduce outliers by finding the most similar topic embeddings
    elif strategy.lower() == "embeddings":
        if topic_model.embedding_model is None and embeddings is None:
            raise ValueError(
                "To use this strategy, you will need to pass a model to `embedding_model`"
                "when instantiating BERTopic."
            )
        outlier_ids = [index for index, topic in enumerate(topics) if topic == -1]
        if images is not None:
            outlier_docs = [images[index] for index in outlier_ids]
        else:
            outlier_docs = [documents[index] for index in outlier_ids]

        # Extract or calculate embeddings for outlier documents
        if embeddings is not None:
            outlier_embeddings = np.array([embeddings[index] for index in outlier_ids])
        elif images is not None:
            outlier_images = [images[index] for index in outlier_ids]
            outlier_embeddings = topic_model.embedding_model.embed_images(
                outlier_images, verbose=topic_model.verbose
            )
        else:
            outlier_embeddings = topic_model.embedding_model.embed_documents(outlier_docs)
        similarity = cosine_similarity(
            outlier_embeddings, topic_model.topic_embeddings_[topic_model._outliers :]
        )

        # Update topics
        similarity[similarity < threshold] = 0
        outlier_topics = iter([np.argmax(sim) if sum(sim) > 0 else -1 for sim in similarity])
        new_topics = [topic if topic != -1 else next(outlier_topics) for topic in topics]

    return new_topics
